interface WeatherIconsDictionary {
  [key: string]: {
    icon: string;
    iconify: string;
    label: string;
  };
}

export const weatherIcons: WeatherIconsDictionary = {
  '200': { icon: 'wi-owm-night-200', iconify: 'owm-night-200', label: 'night-alt-thunderstorm' },
  '201': { icon: 'wi-owm-night-201', iconify: 'owm-night-201', label: 'night-alt-thunderstorm' },
  '202': { icon: 'wi-owm-night-202', iconify: 'owm-night-202', label: 'night-alt-thunderstorm' },
  '210': { icon: 'wi-owm-night-210', iconify: 'owm-night-210', label: 'night-alt-lightning' },
  '211': { icon: 'wi-owm-night-211', iconify: 'owm-night-211', label: 'night-alt-lightning' },
  '212': { icon: 'wi-owm-night-212', iconify: 'owm-night-212', label: 'night-alt-lightning' },
  '221': { icon: 'wi-owm-night-221', iconify: 'owm-night-221', label: 'night-alt-lightning' },
  '230': { icon: 'wi-owm-night-230', iconify: 'owm-night-230', label: 'night-alt-thunderstorm' },
  '231': { icon: 'wi-owm-night-231', iconify: 'owm-night-231', label: 'night-alt-thunderstorm' },
  '232': { icon: 'wi-owm-night-232', iconify: 'owm-night-232', label: 'night-alt-thunderstorm' },
  '300': { icon: 'wi-owm-night-300', iconify: 'owm-night-300', label: 'night-alt-sprinkle' },
  '301': { icon: 'wi-owm-night-301', iconify: 'owm-night-301', label: 'night-alt-sprinkle' },
  '302': { icon: 'wi-owm-night-302', iconify: 'owm-night-302', label: 'night-alt-rain' },
  '310': { icon: 'wi-owm-night-310', iconify: 'owm-night-310', label: 'night-alt-rain' },
  '311': { icon: 'wi-owm-night-311', iconify: 'owm-night-311', label: 'night-alt-rain' },
  '312': { icon: 'wi-owm-night-312', iconify: 'owm-night-312', label: 'night-alt-rain' },
  '313': { icon: 'wi-owm-night-313', iconify: 'owm-night-313', label: 'night-alt-rain' },
  '314': { icon: 'wi-owm-night-314', iconify: 'owm-night-314', label: 'night-alt-rain' },
  '321': { icon: 'wi-owm-night-321', iconify: 'owm-night-321', label: 'night-alt-sprinkle' },
  '500': { icon: 'wi-owm-night-500', iconify: 'owm-night-500', label: 'night-alt-sprinkle' },
  '501': { icon: 'wi-owm-night-501', iconify: 'owm-night-501', label: 'night-alt-rain' },
  '502': { icon: 'wi-owm-night-502', iconify: 'owm-night-502', label: 'night-alt-rain' },
  '503': { icon: 'wi-owm-night-503', iconify: 'owm-night-503', label: 'night-alt-rain' },
  '504': { icon: 'wi-owm-night-504', iconify: 'owm-night-504', label: 'night-alt-rain' },
  '511': { icon: 'wi-owm-night-511', iconify: 'owm-night-511', label: 'night-alt-rain-mix' },
  '520': { icon: 'wi-owm-night-520', iconify: 'owm-night-520', label: 'night-alt-showers' },
  '521': { icon: 'wi-owm-night-521', iconify: 'owm-night-521', label: 'night-alt-showers' },
  '522': { icon: 'wi-owm-night-522', iconify: 'owm-night-522', label: 'night-alt-showers' },
  '531': { icon: 'wi-owm-night-531', iconify: 'owm-night-531', label: 'night-alt-storm-showers' },
  '600': { icon: 'wi-owm-night-600', iconify: 'owm-night-600', label: 'night-alt-snow' },
  '601': { icon: 'wi-owm-night-601', iconify: 'owm-night-601', label: 'night-alt-sleet' },
  '602': { icon: 'wi-owm-night-602', iconify: 'owm-night-602', label: 'night-alt-snow' },
  '611': { icon: 'wi-owm-night-611', iconify: 'owm-night-611', label: 'night-alt-rain-mix' },
  '612': { icon: 'wi-owm-night-612', iconify: 'owm-night-612', label: 'night-alt-rain-mix' },
  '615': { icon: 'wi-owm-night-615', iconify: 'owm-night-615', label: 'night-alt-rain-mix' },
  '616': { icon: 'wi-owm-night-616', iconify: 'owm-night-616', label: 'night-alt-rain-mix' },
  '620': { icon: 'wi-owm-night-620', iconify: 'owm-night-620', label: 'night-alt-rain-mix' },
  '621': { icon: 'wi-owm-night-621', iconify: 'owm-night-621', label: 'night-alt-snow' },
  '622': { icon: 'wi-owm-night-622', iconify: 'owm-night-622', label: 'night-alt-snow' },
  '701': { icon: 'wi-owm-night-701', iconify: 'owm-night-701', label: 'night-alt-showers' },
  '711': { icon: 'wi-owm-night-711', iconify: 'owm-night-711', label: 'smoke' },
  '721': { icon: 'wi-owm-night-721', iconify: 'owm-night-721', label: 'day-haze' },
  '731': { icon: 'wi-owm-night-731', iconify: 'owm-night-731', label: 'dust' },
  '741': { icon: 'wi-owm-night-741', iconify: 'owm-night-741', label: 'night-fog' },
  '761': { icon: 'wi-owm-night-761', iconify: 'owm-night-761', label: 'dust' },
  '762': { icon: 'wi-owm-night-762', iconify: 'owm-night-762', label: 'dust' },
  '771': { icon: 'wi-owm-771', iconify: 'owm-771', label: 'cloudy-gusts' },
  '781': { icon: 'wi-owm-night-781', iconify: 'owm-night-781', label: 'tornado' },
  '800': { icon: 'wi-owm-night-800', iconify: 'owm-night-800', label: 'night-clear' },
  '801': { icon: 'wi-owm-night-801', iconify: 'owm-night-801', label: 'night-alt-cloudy-gusts' },
  '802': { icon: 'wi-owm-night-802', iconify: 'owm-night-802', label: 'night-alt-cloudy-gusts' },
  '803': { icon: 'wi-owm-night-803', iconify: 'owm-night-803', label: 'night-alt-cloudy-gusts' },
  '804': { icon: 'wi-owm-night-804', iconify: 'owm-night-804', label: 'night-alt-cloudy' },
  '900': { icon: 'wi-owm-night-900', iconify: 'owm-night-900', label: 'tornado' },
  '901': { icon: 'wi-owm-901', iconify: 'owm-901', label: 'storm-showers' },
  '902': { icon: 'wi-owm-night-902', iconify: 'owm-night-902', label: 'hurricane' },
  '903': { icon: 'wi-owm-night-903', iconify: 'owm-night-903', label: 'snowflake-cold' },
  '904': { icon: 'wi-owm-night-904', iconify: 'owm-night-904', label: 'hot' },
  '905': { icon: 'wi-owm-905', iconify: 'owm-905', label: 'windy' },
  '906': { icon: 'wi-owm-night-906', iconify: 'owm-night-906', label: 'night-alt-hail' },
  '957': { icon: 'wi-owm-night-957', iconify: 'owm-night-957', label: 'strong-wind' },
};
